# Generated by Django 3.0.11 on 2021-06-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
            ],
        ),
    ]
