# Generated by Django 3.0.11 on 2021-06-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0002_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to='short.Sign'),
        ),
    ]
